apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil
  template:
    metadata:
      labels:
        app: wil
    spec:
      containers:
        - name: wil
          image: wil42/playground:v2
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wil-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: wil
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-ing
  namespace: dev
spec:
  # ingressClassName: nginx
  rules:
    - host: wil.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wil-svc
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  # annotations:
  #   traefik.ingress.kubernetes.io/router.entrypoints: websecure
  #   traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  # tls:
  # - hosts:
  #   - argocd.127.0.0.1.nip.io
  rules:
  - host: argocd.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80

