# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-tls-config
#   namespace: dev
# data:
#   default.conf: |
#     server {
#         listen 443 ssl;
#         server_name nginx.local;

#         ssl_certificate     /etc/nginx/ssl/selfsigned.crt;
#         ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

#         location / {
#             root /usr/share/nginx/html;
#             index index.html;
#         }
#     }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 443
          volumeMounts:
            - name: tls-cert
              mountPath: "/etc/nginx/ssl"
              readOnly: true
            # - name: nginx-conf
            #   mountPath: "/etc/nginx/conf.d"
            #   readOnly: true
      volumes:
        - name: tls-cert
          secret:
            secretName: nginx-tls-secret
        # - name: nginx-conf
        #   configMap:
        #     name: nginx-tls-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
